### ISSUE TITLE
whats the use for this?

### ISSUE THREAD

**Issue by merzaths** [starshipsysteams/tf2-cheater-list#1]
this is dumb, cheaters can just change their name every time, and a lot of the name is common, so really, non cheater and a cheater, can have the same name
and if u think its useful for automation leave if there anyone that has the name on the list, i think its gonna be hard to find a match without one, and even u find one match, theres probably still one cheater lol.
tf2 is a dead game full of cheater anyway, its to become one, or just dont complaint
(sorry if u find it offending, its just my opinion, i find it stupid having a list of all the cheater on a game full of cheater)

**Comment by starshipsystems** [comment]
Um it has steam ids as well

**Comment by starshipsystems** [comment]
Closed!
